######################################################################
# Automatically generated by qmake (3.0) Mon Feb 15 14:15:56 2016
######################################################################

CONFIG += c++11
TEMPLATE = app
TARGET = polyomino
INCLUDEPATH += .

# Input
HEADERS += polyominoes.h
SOURCES += main.cpp polyominoes.cpp
